org: oskstr
app: spam
service: spam

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
      Resource: "*"
  region: eu-west-1
  runtime: nodejs12.x
  stage: dev
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: 20201221

functions:
  ping:
    handler: dist/src/api.ping
    events:
      - http:
          path: api/ping
          method: GET
          cors: true
  send-mail:
    handler: dist/src/api.sendMail
    events:
      - http:
          path: api/sendmail
          method: POST
          cors: true
          request:
            schema: ${file(models/email.yml)}

